name: CI

on:
  push

jobs:
  call_test:
    name: Test on Julia ${{ matrix.version }} - ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.8"  # Minimum compatible Release
          - "1"    # Latest Release
        os:
          - ubuntu-latest
          - windows-latest
        python-version: ["3.11"]
    uses: ./.github/workflows/Test.yml
    with:
      host-os: ${{ matrix.os }}
      julia-version: ${{ matrix.version }}
      python-version: ${{ matrix.python-version }}
    secrets: inherit
  Documenter:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          julia ./.install_spinedb_api.jl
          julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
